[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hoe_dex_protection = "EPKa5m6izBgWC3eJBL7zYYybNDgdB29wzpyeeGZNM6cV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/robin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
